module.exports = {
  env: {
    FIREBASE_API_KEY: process.env.FIREBASE_API_KEY,
    FIREBASE_AUTH_DOMAIN: process.env.FIREBASE_AUTH_DOMAIN,
    FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
    FIREBASE_STORAGE_BUCKET: process.env.FIREBASE_STORAGE_BUCKET,
    FIREBASE_MESSAGING_SENDER_ID: process.env.FIREBASE_MESSAGING_SENDER_ID,
    FIREBASE_APP_ID: process.env.FIREBASE_APP_ID,
    FIREBASE_MEASUREMENT_ID: process.env.FIREBASE_MEASUREMENT_ID,
    NOTION_FIRST_INTEGRATION: process.env.NOTION_FIRST_INTEGRATION,
    NOTION_API_TEST_DBID: process.env.NOTION_API_TEST_DBID,
    GPC_GOOGLE_MAP_API_KEY: process.env.GPC_GOOGLE_MAP_API_KEY,
		NOTION_KEY: process.env.NOTION_KEY,
		NOTION_DATABASE_ID: process.env.NOTION_DATABASE_ID,
		NOTION_API_KEY: process.env.NOTION_API_KEY,
  }
}


