import Head from 'next/head'
import Link from 'next/link'
import btn from './component/button'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Top Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex justify-center">
          <h1>Welcome to <a href="https://nextjs.org">Next.js!</a></h1>
        </div>
      </main>

      { btn("index") }
    </div>
  )
}
